### ISSUE TITLE
[FEAT] Create contributing.md

### ISSUE THREAD

**Issue by Romakita** [TypedProject/vuepress-theme-tsed#36]
You can take as example: https://github.com/TypedProject/tsed/blob/production/CONTRIBUTING.md

## Acceptance criteria

- [x] Replace mail contact by gitter link https://gitter.im/Tsed-io/community
- [x] Replace Tsed by vuepress-theme-tsed

**Comment by confusedcoder1** [comment]
Hey, I'd like to work on this. Will you be assigning it to people or wait for PRs?
